create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  serial_number text unique not null,
  id_number text not null,
  document_type text not null,
  file_path text,
  file_size bigint,
  mime_type text,
  status text not null check (status in ('active', 'expired', 'revoked')) default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.verification_attempts (
  id bigint generated by default as identity primary key,
  serial_number text not null,
  id_number text not null,
  status text not null check (status in ('success', 'failed')),
  created_at timestamptz not null default now()
);

alter table public.documents enable row level security;
alter table public.verification_attempts enable row level security;

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;
